# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'xample_gui.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Xample_gui(object):
    def setupUi(self, Xample_gui):
        Xample_gui.setObjectName("Xample_gui")
        Xample_gui.resize(988, 644)
        self.centralWidget = QtWidgets.QWidget(Xample_gui)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.pushButton_add = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_add.setObjectName("pushButton_add")
        self.gridLayout.addWidget(self.pushButton_add, 6, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 5, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 3, 1, 1)
        self.doubleSpinBox_mult_02 = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.doubleSpinBox_mult_02.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_mult_02.setDecimals(3)
        self.doubleSpinBox_mult_02.setMinimum(-999999999.0)
        self.doubleSpinBox_mult_02.setMaximum(999999999.0)
        self.doubleSpinBox_mult_02.setObjectName("doubleSpinBox_mult_02")
        self.gridLayout.addWidget(self.doubleSpinBox_mult_02, 4, 4, 1, 1)
        self.label_time = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_time.setFont(font)
        self.label_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time.setObjectName("label_time")
        self.gridLayout.addWidget(self.label_time, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 3, 1, 1)
        self.doubleSpinBox_mult_01 = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.doubleSpinBox_mult_01.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_mult_01.setDecimals(3)
        self.doubleSpinBox_mult_01.setMinimum(-999999999.0)
        self.doubleSpinBox_mult_01.setMaximum(999999999.0)
        self.doubleSpinBox_mult_01.setObjectName("doubleSpinBox_mult_01")
        self.gridLayout.addWidget(self.doubleSpinBox_mult_01, 3, 4, 1, 1)
        self.doubleSpinBox_add_01 = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.doubleSpinBox_add_01.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_add_01.setDecimals(3)
        self.doubleSpinBox_add_01.setMinimum(-999999999.0)
        self.doubleSpinBox_add_01.setMaximum(999999999.0)
        self.doubleSpinBox_add_01.setObjectName("doubleSpinBox_add_01")
        self.gridLayout.addWidget(self.doubleSpinBox_add_01, 3, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 1, 1, 1)
        self.doubleSpinBox_add_02 = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.doubleSpinBox_add_02.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_add_02.setDecimals(3)
        self.doubleSpinBox_add_02.setMinimum(-999999999.0)
        self.doubleSpinBox_add_02.setMaximum(999999999.0)
        self.doubleSpinBox_add_02.setObjectName("doubleSpinBox_add_02")
        self.gridLayout.addWidget(self.doubleSpinBox_add_02, 4, 1, 1, 1)
        self.pushButton_multiply = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_multiply.setObjectName("pushButton_multiply")
        self.gridLayout.addWidget(self.pushButton_multiply, 6, 3, 1, 1)
        self.label_result_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_result_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_result_2.setObjectName("label_result_2")
        self.gridLayout.addWidget(self.label_result_2, 6, 4, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 5, 3, 1, 2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 0, 1, 1)
        self.label_result_1 = QtWidgets.QLabel(self.centralWidget)
        self.label_result_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_result_1.setObjectName("label_result_1")
        self.gridLayout.addWidget(self.label_result_1, 6, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 2, 5, 1, 1)
        self.horizontalLayout_plot_random_stuff = QtWidgets.QHBoxLayout()
        self.horizontalLayout_plot_random_stuff.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_plot_random_stuff.setSpacing(6)
        self.horizontalLayout_plot_random_stuff.setObjectName("horizontalLayout_plot_random_stuff")
        self.gridLayout.addLayout(self.horizontalLayout_plot_random_stuff, 1, 1, 2, 4)
        self.verticalLayout.addLayout(self.gridLayout)
        Xample_gui.setCentralWidget(self.centralWidget)

        self.retranslateUi(Xample_gui)
        QtCore.QMetaObject.connectSlotsByName(Xample_gui)

    def retranslateUi(self, Xample_gui):
        _translate = QtCore.QCoreApplication.translate
        Xample_gui.setWindowTitle(_translate("Xample_gui", "Xample_gui"))
        self.pushButton_add.setText(_translate("Xample_gui", "add"))
        self.label_2.setText(_translate("Xample_gui", " first number:"))
        self.label_3.setText(_translate("Xample_gui", " second number:"))
        self.label_5.setText(_translate("Xample_gui", " first number:"))
        self.label_time.setText(_translate("Xample_gui", "00:00:00"))
        self.label_6.setText(_translate("Xample_gui", " second number:"))
        self.pushButton_multiply.setText(_translate("Xample_gui", "multiply"))
        self.label_result_2.setText(_translate("Xample_gui", "0"))
        self.label_result_1.setText(_translate("Xample_gui", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Xample_gui = QtWidgets.QMainWindow()
    ui = Ui_Xample_gui()
    ui.setupUi(Xample_gui)
    Xample_gui.show()
    sys.exit(app.exec_())

